### ISSUE TITLE
GPIO pin mapping

### ISSUE THREAD

**Issue by jemgoss** [romilly/quick2wire-python-api#12] opened 2012-12-07 22:09 UTC
In gpio.py, I believe the last two entries in RaspberryPi_HeaderToSOC should be changed from:

25: 7,
26: 8

to

24: 8,
26: 7

(25 is GND and 26 is 7, not 8).

(While you're at it, you might want to fix the doc in exported() to read ... and _un_exports it at the end of the block...)

**Comment by npryce** [comment] 2012-12-21 19:45
Duplicate of #16

**Closed as completed by npryce** 2012-12-21 19:45 UTC
Labels: bug, duplicate

**Comment by jemgoss** [comment] 2013-01-14 21:55
This issue is not a duplicate of #16. I was waiting to see if it was rolled into the fix for #16 but it hasn't been fixed yet.

This issue is about incorrect pin mappings for header pins 24,25,26 and is not specific to board revision.
Currenty, gpio.py maps header pins 25 and 26. 25 is actually GND. The mapping should be 24 -> 8, 26 -> 7.
I've got a project that needs all the gpio pins available so I need to use pin 24 and 26.

Thanks for looking into this.

**Comment by npryce** [comment] 2013-01-15 02:07
If you can send us a pull request that'll help us fix this quicker.
