### ISSUE TITLE
No module named quick2wire.gpio

### ISSUE THREAD

**Issue by richardwillars** [romilly/quick2wire-python-api#15] opened 2012-12-18 10:34 UTC
This is probably quite an easy one to fix but thought it might need documenting as I expect quite a few people to run into this issue.

Here's what I did from a clean install:
- Installed quick2wire-gpio-admin by following the instructions found on http://quick2wire.com/articles/how-to-add-quick2wire-as-a-raspbian-software-source/
- Ran 'sudo adduser $USER gpio' and then rebooted the pi.
- Downloaded quick2wire-python-api
- Ran 'export QUICK2WIRE_API_HOME=/home/pi/lib/quick2wire-python-api'
  -Ran 'export PYTHONPATH=$PYTHONPATH:$QUICK2WIRE_API_HOME/src'
- Copied the code from https://github.com/quick2wire/quick2wire-python-api/blob/master/examples/epoll into a new python file and ran it from the command line
- I get the error message 'No module named quick2wire.gpio' on the 'from quick2wire.gpio import Pin' line

Any ideas what I'm doing wrong? Have I missed something out?

**Comment by npryce** [comment] 2012-12-18 15:10
How did you run it?  Did you run with the python3 interpreter?

**Comment by richardwillars** [comment] 2012-12-18 15:28
I ran it from the command line using:

python epollTest.py

I presume it's Python v3 as it's a just downloaded copy of the Raspberry Pi distro which I believe has Python v3 installed.

**Comment by npryce** [comment] 2012-12-18 15:55
In the image I have, the python command runs Python 2.7.  Can you try with the python3 command instead?

Thanks.

**Comment by richardwillars** [comment] 2012-12-18 16:37
Ah right, didn't realise there were multiple versions installed!

Unfortunately running python3 epollTest.py gives the same error message as before.

**Comment by npryce** [comment] 2012-12-18 17:37
Does the file /home/pi/lib/quick2wire-python-api/src/quick2wire/gpio.py exist?

What about /home/pi/lib/quick2wire-python-api/src/quick2wire/**init**.py?

Could you paste the output from 'ls -lR /home/pi/lib/quick2wire-python-api/' here?

Also, what is the value of the PYTHONPATH environment variable?

**Comment by richardwillars** [comment] 2012-12-21 10:01
Whilst trying to fix this I moved the entire library to  I've moved it the library dir to /home/pi/Wheel/quick2wire-python-api-master.

Does the file /home/pi/Wheel/quick2wire-python-api-master/src/quick2wire/gpio.py exist?
Yes -

What about /home/pi/lib/quick2wire-python-api-master/src/quick2wire/**init**.py?
Yes - As above

Directory listing: http://pastie.org/5560719

PYTHONPATH - struggled to work out how to output this. In the end I've only managed to get it for Python 2.7 but not for Python 3.0 (print sys.path doesn't work in v3):
['/home/pi/Desktop', '/home/pi/Desktop', '/home/pi/Wheel/quick2wire-python-api-master/src', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']

**Comment by richardwillars** [comment] 2012-12-21 10:05
Fixed it! The file owner and group were set to root for every file in the directory. I used "sudo chgrp -R pi /home/pi/Wheel/quick2wire-python-api-master" and "sudo chown -R pi /home/pi/Wheel/quick2wire-python-api-master" to change the permissions and it now works fine :)

It might be worth adding these commands to the installation guide so other users don't fall into that trap.

Thanks for the help!

**Comment by richardwillars** [comment] 2012-12-21 10:18
Unforutnately it doesn't appear to be the end of the problem. When you execute the python script over SSH (logged in as pi) rather than through a local command line you get the same error as before (which seems odd seeing as you're SSH'd in as 'pi' and all the files/dirs are owned by 'pi'!

**Comment by npryce** [comment] 2012-12-21 19:41
Very strange that your checked out files were all owned by root.   Did you accidentally use sudo when doing the checkout?

I recommend not running as the pi user, because it has root privileges. Instead, create a new user with the adduser command, add it to the sudo, gpio and i2c groups, and then log out and back in in as that new user to use the Pi for day-to-day work.

**Comment by npryce** [comment] 2012-12-21 19:44
Closing the issue because it appears to be caused by permissions on your Raspberry Pi.

**Closed as completed by npryce** 2012-12-21 19:44 UTC
Labels: invalid
